# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170402_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='access_token',
        ),
    ]
