# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20170404_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='user_type',
            field=models.CharField(choices=[('GOOGLE', 'g'), ('FACEBOOK', 'f'), ('NORMAL', 'n')], default='n', max_length=8),
        ),
    ]
