# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20170404_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='user_type',
            field=models.CharField(choices=[('GOOGLE', 'google'), ('FACEBOOK', 'facebook'), ('NORMAL', 'normal')], default='normal', max_length=8),
        ),
    ]
