# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20170406_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='access_token',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='member',
            name='introduction',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='member',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='member',
            name='nickname',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='user_type',
            field=models.CharField(choices=[('GOOGLE', 'google'), ('FACEBOOK', 'facebook'), ('NORMAL', 'normal')], default='NORMAL', max_length=8),
        ),
    ]
