# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20170419_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='access_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
