# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postphoto',
            name='photo',
            field=models.FileField(upload_to='post'),
        ),
    ]
