# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20170414_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default='2017-04-14 12:35'),
        ),
    ]
