# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20170408_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postphoto',
            name='photo',
            field=models.ImageField(upload_to='post'),
        ),
    ]
