# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20170419_0042'),
        ('diary', '0004_auto_20170418_1559'),
    ]

    operations = [
    ]
