# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_merge_20170420_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default='2017-04-20 01:32'),
        ),
    ]
